name: 'Build LithOS Image'

on:
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout LithOS
        uses: actions/checkout@v3
        with:
          path: main
        
      - name: Clone kas
        uses: actions/checkout@v3
        with:
          repository: siemens/kas
          path: kas
      
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
        
      - name: Check Docker Version
        run: |
            set -x
            docker version
      
      - name: Build OS Image
        run: kas/kas-container build main/kirkstone.yaml

      - name: Check disk usage after build
        run: df -h

      - name: Pack
        run: |
            cd ${{ github.workspace }}/poky/build/tmp
            tar -Jcf lithos.tar.xz deploy/images
            echo "PACKAGE=${{ github.workspace }}/poky/build/tmp/lithos.tar.xz" >> $GITHUB_ENV
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Test upload-to-github-release works with ```actions/create-release```
          draft: true
          prerelease: false
      
      - uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.md;*.zip;random-name-*.txt"
          delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
